/**
 * AdaptHealth Partner APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Custom
 */
interface Custom {
  /**
   * a unique identifier for this particular occurrence of the problem.
   * https://docs.mulesoft.com/mule-runtime/4.4/correlation-id
   */
  correlationId: string;
  /** the HTTP status code applicable to this problem, expressed as a string value. */
  status: string;
  /** an application-specific error code, expressed as a string value. */
  code?: string;
  /** a short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization. */
  title: string;
  /** a human-readable explanation specific to this occurrence of the problem. Like title, this field’s value can be localized. */
  detail?: string;
  /** an object containing references to the source of the error */
  source?: string;
  /** a meta object containing non-standard meta-information about the error. */
  meta?: unknown;
  [key: string]: unknown;
}

export class CustomError extends ApiError<Custom> {}
