/**
 * AdaptHealth Partner APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AddressTypeEnum
 */
export enum AddressTypeEnum {
  Delivery = 'delivery',
  Billing = 'billing',
  Physical = 'physical',
}

/**
 * Schema for AddressTypeEnum
 */
export const addressTypeEnumSchema: Schema<AddressTypeEnum> = stringEnum(AddressTypeEnum);
