/**
 * AdaptHealth Partner APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, expandoObject, lazy, Schema, string } from '../schema';
import { Response, responseSchema } from './response';

export interface ApiResponse1 {
  success: boolean;
  apiName: string;
  version: string;
  timeStamp: string;
  correlationId: string;
  response: Response;
  [key: string]: unknown;
}

export const apiResponse1Schema: Schema<ApiResponse1> = expandoObject({
  success: ['success', boolean()],
  apiName: ['apiName', string()],
  version: ['version', string()],
  timeStamp: ['timeStamp', string()],
  correlationId: ['correlationId', string()],
  response: ['response', lazy(() => responseSchema)],
});
