/**
 * AdaptHealth Partner APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, Schema, string } from '../schema';
import { ClassTypeEnum, classTypeEnumSchema } from './classTypeEnum';

/** Coverage Classification */
export interface Class {
  type: ClassTypeEnum;
  value: string;
  name: string;
  [key: string]: unknown;
}

export const classSchema: Schema<Class> = expandoObject({
  type: ['type', classTypeEnumSchema],
  value: ['value', string()],
  name: ['name', string()],
});
