/**
 * AdaptHealth Partner APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ContactPointUseEnum
 */
export enum ContactPointUseEnum {
  Delivery = 'delivery',
  Billing = 'billing',
  Mobile = 'mobile',
}

/**
 * Schema for ContactPointUseEnum
 */
export const contactPointUseEnumSchema: Schema<ContactPointUseEnum> = stringEnum(ContactPointUseEnum);
