/**
 * AdaptHealth Partner APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for GenderEnum
 */
export enum GenderEnum {
  Male = 'male',
  Female = 'female',
  Other = 'other',
  Unknown = 'unknown',
}

/**
 * Schema for GenderEnum
 */
export const genderEnumSchema: Schema<GenderEnum> = stringEnum(GenderEnum);
