/**
 * AdaptHealth Partner APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  expandoObject,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface HealthResponse {
  /** The name of the MuleSoft app or external system being checked */
  serviceName: string;
  /** true or false if the system responds */
  connected: boolean;
  /** Deployed version id of the MuleSoft app or external system being checked */
  serviceVersion: string;
  /** Additional information especially if the system is not responding correctly */
  detail?: string;
  /** Any connected services that also hit their /health endpoint will embed results in the connectedServices array with same format */
  connectedServices?: unknown[];
  [key: string]: unknown;
}

export const healthResponseSchema: Schema<HealthResponse> = expandoObject({
  serviceName: ['serviceName', string()],
  connected: ['connected', boolean()],
  serviceVersion: ['serviceVersion', string()],
  detail: ['detail', optional(string())],
  connectedServices: ['connectedServices', optional(array(unknown()))],
});
