/**
 * AdaptHealth Partner APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for IdentifierUseEnum
 */
export enum IdentifierUseEnum {
  Internal = 'internal',
  External = 'external',
  Source = 'source',
  Destination = 'destination',
  Other = 'other',
}

/**
 * Schema for IdentifierUseEnum
 */
export const identifierUseEnumSchema: Schema<IdentifierUseEnum> = stringEnum(IdentifierUseEnum);
