/**
 * AdaptHealth Partner APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for IdentifierTypeEnum
 */
export enum IdentifierTypeEnum {
  Patient = 'patient',
  Cpt = 'cpt',
  Order = 'order',
  NPI = 'NPI',
  Payor = 'payor',
}

/**
 * Schema for IdentifierTypeEnum
 */
export const identifierTypeEnumSchema: Schema<IdentifierTypeEnum> = stringEnum(IdentifierTypeEnum);
