/**
 * AdaptHealth Partner APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, Schema, string } from '../schema';

/** a date-only range */
export interface Period {
  start: string;
  end: string;
  [key: string]: unknown;
}

export const periodSchema: Schema<Period> = expandoObject({
  start: ['start', string()],
  end: ['end', string()],
});
