/**
 * AdaptHealth Partner APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, lazy, Schema, string } from '../schema';
import { Address, addressSchema } from './address';
import { GenderEnum, genderEnumSchema } from './genderEnum';
import { HumanName, humanNameSchema } from './humanName';

export interface PolicyHolder {
  name: HumanName;
  birthdate: string;
  gender: GenderEnum;
  address: Address;
  [key: string]: unknown;
}

export const policyHolderSchema: Schema<PolicyHolder> = expandoObject({
  name: ['name', lazy(() => humanNameSchema)],
  birthdate: ['birthdate', string()],
  gender: ['gender', genderEnumSchema],
  address: ['address', lazy(() => addressSchema)],
});
