/**
 * AdaptHealth Partner APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, Schema } from '../schema';
import { Address, addressSchema } from './address';
import { ContactPoint, contactPointSchema } from './contactPoint';
import { HumanName, humanNameSchema } from './humanName';
import { Identifier, identifierSchema } from './identifier';
import { Qualification, qualificationSchema } from './qualification';

export interface Practicioner {
  identifier: Identifier[];
  name: HumanName;
  telecom: ContactPoint;
  address: Address;
  qualification: Qualification[];
  [key: string]: unknown;
}

export const practicionerSchema: Schema<Practicioner> = expandoObject({
  identifier: ['identifier', array(lazy(() => identifierSchema))],
  name: ['name', lazy(() => humanNameSchema)],
  telecom: ['telecom', lazy(() => contactPointSchema)],
  address: ['address', lazy(() => addressSchema)],
  qualification: ['qualification', array(lazy(() => qualificationSchema))],
});
