/**
 * AdaptHealth Partner APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, Schema } from '../schema';
import { Identifier, identifierSchema } from './identifier';

/** provider qualifications, including NPI, Medicaid numbers, etc. */
export interface Qualification {
  identifier: Identifier[];
  [key: string]: unknown;
}

export const qualificationSchema: Schema<Qualification> = expandoObject({
  identifier: ['identifier', array(lazy(() => identifierSchema))],
});
