/**
 * AdaptHealth Partner APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, number, Schema, string } from '../schema';

export interface Quantity {
  quantity: number;
  unit: string;
  [key: string]: unknown;
}

export const quantitySchema: Schema<Quantity> = expandoObject({
  quantity: ['quantity', number()],
  unit: ['unit', string()],
});
