/**
 * AdaptHealth Partner APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, Schema } from '../schema';
import { Identifier, identifierSchema } from './identifier';
import {
  ReferenceTypeEnum,
  referenceTypeEnumSchema,
} from './referenceTypeEnum';

/** a reference to another entity, typically with the resource identifier included */
export interface Reference {
  type: ReferenceTypeEnum;
  identifier: Identifier[];
  [key: string]: unknown;
}

export const referenceSchema: Schema<Reference> = expandoObject({
  type: ['type', referenceTypeEnumSchema],
  identifier: ['identifier', array(lazy(() => identifierSchema))],
});
