/**
 * AdaptHealth Partner APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for RelationshipEnum
 */
export enum RelationshipEnum {
  Self = 'self',
  Child = 'child',
  Spouse = 'spouse',
  Other = 'other',
}

/**
 * Schema for RelationshipEnum
 */
export const relationshipEnumSchema: Schema<RelationshipEnum> = stringEnum(RelationshipEnum);
