/**
 * AdaptHealth Partner APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, Schema, string, unknown } from '../schema';

export interface Response {
  message: string;
  data?: unknown;
  [key: string]: unknown;
}

export const responseSchema: Schema<Response> = expandoObject({
  message: ['message', string()],
  data: ['data', unknown()],
});
