/**
 * AdaptHealth Partner APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, number, Schema, unknown } from '../schema';

export interface SearchResponse {
  currentPage: number;
  pageSize: number;
  totalRecordCount: number;
  data?: unknown;
  [key: string]: unknown;
}

export const searchResponseSchema: Schema<SearchResponse> = expandoObject({
  currentPage: ['currentPage', number()],
  pageSize: ['pageSize', number()],
  totalRecordCount: ['totalRecordCount', number()],
  data: ['data', unknown()],
});
