/**
 * AdaptHealth Partner APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, expandoObject, lazy, Schema } from '../schema';
import { Identifier, identifierSchema } from './identifier';
import { Quantity, quantitySchema } from './quantity';

/** procedures, services, or items requested */
export interface Service {
  identifier: Identifier[];
  quantity: Quantity;
  [key: string]: unknown;
}

export const serviceSchema: Schema<Service> = expandoObject({
  identifier: ['identifier', array(lazy(() => identifierSchema))],
  quantity: ['quantity', lazy(() => quantitySchema)],
});
