/**
 * AdaptHealth Partner APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for StatusEnum
 */
export enum StatusEnum {
  Submitted = 'submitted',
  Active = 'active',
  Onhold = 'on-hold',
  Revoked = 'revoked',
  Completed = 'completed',
  Enteredinerror = 'entered-in-error',
  Unknown = 'unknown',
}

/**
 * Schema for StatusEnum
 */
export const statusEnumSchema: Schema<StatusEnum> = stringEnum(StatusEnum);
