/**
 * AdaptHealth Partner APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SystemEnum
 */
export enum SystemEnum {
  Phone = 'phone',
  Email = 'email',
  Fax = 'fax',
}

/**
 * Schema for SystemEnum
 */
export const systemEnumSchema: Schema<SystemEnum> = stringEnum(SystemEnum);
